spring.application.name=tastory

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tastory_db}
spring.datasource.username=${DB_USERNAME:tastory_user}
spring.datasource.password=${DB_PASSWORD:tastory_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

tastory.admin.email=${ADMIN_EMAIL:admin@tastory.gr}
tastory.admin.password=${ADMIN_PASSWORD:admin123}